export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDRIENTS';
export const SET_INGREDIENTS_FAILED = 'SET_INGREDRIENTS_FAILED';